#!/usr/bin/env python2

import rospy
from sensor_msgs.msg import Image

def callback(msg):
    print("got message: {}".format(msg))

if __name__ == '__main__':
    rospy.init_node('recorder')
    print("hello")
    rospy.Subscriber("/camera_input", Image, callback )
    rospy.spin()